### ISSUE TITLE
Font not working on firefox family browsers

### ISSUE THREAD

**Issue by patillacode** [patillacode/pimpositor#1]
Even with this css code the font does not render properly on some firefox browsers.

``` css

@font-face {
    font-family: "Swiftel";
    src: url("../fonts/Swiftel.ttf"),
         url('../fonts/Swiftel.woff2') format('woff2'), /* Super Modern Browsers */
         url('../fonts/Swiftel.woff') format('woff'), /* Pretty Modern Browsers */
}
```
